### ISSUE TITLE
抱歉，从前端这一节就不知道怎么做了

### ISSUE THREAD

**Issue by crystoneme** [zuoFeng59556/my-blog#1]
木有npm开发基础，之前的按照你的操作顺利，但是在这节的时候，就不知道需要做什么了

**Comment by zuoFeng59556** [comment]
你好，可以提供更多的信息吗，例如哪一篇文章，哪些地方不明白，最好可以贴上图片哦。

**Comment by yangchuansheng** [comment]
> 

前端那一节只是为了告诉你原理，不是让你真的操作，你实际操作的时候只需要把这个仓库里的前端代码上传到对象存储就行了（如果你不需要修改功能的话~）
